import turtle
t=turtle.Turtle()
t.speed(1)
t.color("#FFF8DC")
wn= turtle.Screen()
wn.title("My First Project in Turtle")
wn.bgcolor("black")
t.pensize(3)
def python_logo(x,y):
    # Here, I draw blue part 
    t.begin_fill()
    t.up()
    t.goto(x,y)
    t.down()
    t.lt(180)
    t.fd(80)
    t.circle(40,80)
    t.lt(10)
    t.fd(40)
    t.circle(40,80)
    t.lt(10)
    t.fd(10)
    t.lt(90)
    t.fd(10)
    t.circle(-40,80)
    t.rt(10)
    t.fd(40)
    t.circle(40,80)
    t.lt(10)
    t.fd(55)
    t.circle(40,80)
    t.lt(10)
    t.fd(40)
    t.circle(40,80)
    t.lt(10)
    t.fd(25)
    t.lt(90)
    t.fd(76)
    t.rt(90)
    t.fd(5)
    t.fillcolor("#4169E1")
    t.end_fill()
    t.lt(90)
    t.up()
    t.fd(40)
    t.down()

    # Here, I draw yellow part
    t.begin_fill()
    t.rt(90)
    t.fd(30)
    t.circle(-40,80)
    t.rt(10)
    t.fd(40)
    t.circle(40,80)
    t.lt(10)
    t.fd(35)
    t.circle(40,80)
    t.lt(10)
    t.fd(40)
    t.circle(40,80)
    t.lt(10)
    t.fd(23)
    t.lt(90)
    t.fd(76)
    t.rt(90)
    t.fd(7)
    t.rt(90)
    t.fd(80)
    t.circle(40,80)
    t.lt(10)
    t.fd(45)
    t.circle(40,80)
    t.lt(10)
    t.fd(10)
    t.fillcolor("#FFD700")
    t.end_fill()

    # Here, I draw dot
    t.up()
    t.home()
    t.goto(0,-60)
    t.down()
    t.begin_fill()
    t.circle(15)
    t.fillcolor("white")
    t.end_fill()
    t.up()
    t.home()
    t.goto(-40,115)
    t.down()
    t.begin_fill()
    t.circle(15)
    t.fillcolor("white")
    t.end_fill()
    t.hideturtle()
  
x,y=0,100
python_logo(x,y)

turtle.done()




